### ISSUE TITLE
Criticas Construtivas!

### ISSUE THREAD

**Issue by JhoanDev** [classroom-ufersa/BubbleSortClientes#1]
1# corrigir as bibliotecas, tem bibliotecas desnecessarias sendo chamadas na main que ja estão sendo chamadas em outras. coloque elas na .h inicial(no caso do projeto de vcs cliente.h). que ai elas vão junto do include.

2# na parte de inserir codigo do cliente garantam que só vai aceitar dados do tipo inteiro.

3# Seria legal salvar no arquivo de forma ordenada também, ou seja sempre reescrever o arquivo após ordenar o array.

4# Utilizar mais de uma branch para não haver commits direto na main, sugiro utilização de git flow, vou anexar o link : [sobre o git flow](https://www.atlassian.com/br/git/tutorials/comparing-workflows/gitflow-workflow)

**Comment by adrianviniciuscs** [comment]
Issue resolvida nos commits [56f02cd](https://github.com/classroom-ufersa/BubbleSortClientes/commit/6a4e4bbc5c1086d4dacf213ce43c7329768d38b3) e [6a4e4bb](https://github.com/classroom-ufersa/BubbleSortClientes/commit/56f02cdb75f7093c71dbd2805ae5767769468093).
